### ISSUE TITLE
Help wanted: Prevent body scroll when modal open

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-modal-window-changelog#1]
How can I hook into the open/close modal events to prevent the body from scrolling while the modal is open?

**Comment by sebastiano-guerriero** [comment]
You can use the modal custom events to add a class (e.g., .overflow-hidden) to the body:
https://codyhouse.co/ds/components/info/modal-window#custom-events

**Comment by emilycritter** [comment]
Thank you!
