### ISSUE TITLE
Trigger modal window in dynamic element

### ISSUE THREAD

**Issue by dhduc** [CodyHouse/cd-modal-window-changelog#2]
Hi guys,
I have been developing a feature using infinite load combine modal window.
So, how can I init modal trigger for new loaded elements from ajax?
I am using Mercurio template.
Thanks.

**Comment by claudia-romano** [comment]
Hi there,
if you are using the [Infinite Scroll component](https://codyhouse.co/ds/components/info/infinite-scroll), you can use the `content-loaded` event to detect when new modal triggers are loaded. More info here:
https://codyhouse.co/ds/components/info/infinite-scroll#path

Once a new trigger is loaded, you can use the `openModal ` custom event to trigger the opening of your modal when clicking on the trigger. Something like:
```
// dynamicTrigger -> modal trigger added using the Inifinite Scroll component
dynamicTrigger.addEventListener('click', function(){
  var event = new CustomEvent('openModal');
  modal.dispatchEvent(event);
});
```

You can find more info on the `openModal` event here:
https://codyhouse.co/ds/components/info/modal-window#custom-events

Cheers!

**Comment by dhduc** [comment]
Hi @claudia-romano, thanks for your supporting.
