### ISSUE TITLE
Open Modal based on <a href="">

### ISSUE THREAD

**Issue by alebarbaja** [CodyHouse/cd-modal-window-changelog#3]
Hi, is possible open the Modal window with an iframe inside based on the source of a link element?
I would like open a modal window using as trigger the <a> element, this works well with the custom event `openModal()`, but how can I open a modal window and inside of this Modal inyect an iframe with the link of the trigger?

Something like this:

```html
<a href="url.com" class="js-modal-trigger">
```

I don't know if with this component, this is possible.
Thanks!

**Comment by claudia-romano** [comment]
Hi Alejandro, the [Modal Video component](https://codyhouse.co/ds/components/app/modal-video) is the one you are looking for. Take a look at the [Info page](https://codyhouse.co/ds/components/info/modal-video) for additional details on using it. Cheers!
