### ISSUE TITLE
Modal will not initialise after pageAnimation Transition

### ISSUE THREAD

**Issue by localoneway** [CodyHouse/cd-modal-window-changelog#4]
1) Short description of the bug - After the page loads after an animated page transition the modal window will not re initialize even after following the steps on the components page. 
  
2) Steps to reproduce the bug - Try to go to a page that has the animated headline on it after an animated page transition and it will not load. Even after trying both versions of this in the afterEnter  
```
// modal
    var modal = newContent.getElementsByClassName('modal');
    if(modal.length > 0) {
      new Modal(modal[0]);
    }
```
or 
```
var modal = document.getElementsByClassName('modal')[0];
new Modal(modal);
```
 
3) Browser + Operating system - I am using both Firefox and Chrome on both Mac OS Big Sur 11.6 as well as Linux Ubuntu 20.04.2 LTS

4) A link to a live demo - https://wonderful-edison-909afa.netlify.app if you click on the home tile titled Team the animation will happen, the slideshows will initialize, but the modal window link at the bottom of the page on the new page will not initiate.
  
5)  (Optional) A screencast/screenshot of the issue - https://user-images.githubusercontent.com/48697608/139510443-7c60a173-fee4-4b08-8bc3-14a74d3b431e.mp4

**Comment by claudia-romano** [comment]
Same as [this issue](https://github.com/CodyHouse/cd-animated-headline-changelog/issues/2).

**Comment by localoneway** [comment]
I believe I found the issue, but am now needing a solution. On my site I am using the off-canvas navigation as well as pageTransition. I have been having issues with initializing the content after a pageTransition. I have figured out how to initialize the animated headline, but I am still having problems with the Modal and I believe it is because the content of my modal is outside of the .off-canvas element. But the pageTranisitions is inside the .off-canvas element and therefore doesn't load the modal content that is lying outside of the .off-canvas element. If I put the pageTransition outside of the off-canvas element nothing works... How I have it everything works, except the modal content never loads on the new page. Thank you for your help.

**Comment by claudia-romano** [comment]
If your modal is outside the `.js-page-trans__content` element, then you do not need to re-initialize it after a page transition. 

If your modal trigger is inside the `.js-page-trans__content`, then you will need to register this new trigger: add an event listener for the click on the trigger, and then use the `openModal` event as explained here:
https://codyhouse.co/ds/components/info/modal-window#custom-events

**Comment by localoneway** [comment]
Hi Claudia! 

Maybe I am not being clear enough, or maybe I am just misunderstanding you. The trigger is inside the .js-page-trans__content and inside of the .off-canvas element, but the content of the modal form content lies outside of the .off-canvas element as you told me to do in a prior email. When the page loads from a pageTransition the modal content that is lying outside of the off-canvas element does not load. as it is only on one page. If I move the modal content inside of the .js-page-trans__content then the modal form appears at the top of the page and not in the correct position.

**Comment by claudia-romano** [comment]
Only the content of the `.js-page-trans__content` element is updated when moving from one page to another. Everything that is outside that element is not removed by the plugin. You can inspect the DOM after a page transition and you'll see that the modal element is still there.

**Comment by localoneway** [comment]
Hello Claudia,

I have still been having  issues with the modal window loading after a page
transition. I can get each component to load correctly after the
pageTranisiton if they are alone on the page after adding some code to the
_2_page-transition_v1.js, but if I add any other component to the page that
the modal is on it will fail to work correctly... I need to have three
slideshows load as well as the modal form.

I am using this in my _2_page-transition_v1.js

Thank You,
Andrew

afterEnter: function(newContent, link) {
// slideshow
var slideshowEl = newContent.getElementsByClassName('slideshow');
if(slideshowEl.length > 0) {
new Slideshow({
element: slideshowEl[0],
navigation: false, // show dots navigation
autoplay : false, // enable/disable autoplay
autoplayInterval : false, // in milliseconds - default is 5000 (5s)
autoplayOnHover: false, // do not pause autoplay on hover
swipe : false // enable/disable swipe
});
new Slideshow({
element: slideshowEl[1],
navigation: false, // show dots navigation
autoplay : false, // enable/disable autoplay
autoplayInterval : false, // in milliseconds - default is 5000 (5s)
autoplayOnHover: false, // do not pause autoplay on hover
swipe : false // enable/disable swipe
});
new Slideshow({
element: slideshowEl[2],
navigation: false, // show dots navigation
autoplay : false, // enable/disable autoplay
autoplayInterval : false, // in milliseconds - default is 5000 (5s)
autoplayOnHover: false, // do not pause autoplay on hover
swipe : false // enable/disable swipe
});
}
// animated headline
var headline = newContent.getElementsByClassName('text-anim');
if(headline.length > 0) {
new TextAnim(headline[1]);
}
// modal
var modal = document.getElementsByClassName('modal')[0];
new Modal(modal);

},
// additional options here
});

**Comment by claudia-romano** [comment]
Hi there, unfortunately I'm not clear what the problem is. 

If you are having an issue with the modal window, please don't mix it with the slideshows as those are not related (unless you have the slideshows in the modal which I assume is not the case).
