### ISSUE TITLE
Trigger modal from dynamically generated navigation

### ISSUE THREAD

**Issue by rjdusk** [CodyHouse/cd-modal-window-changelog#5]
Hi team,
I'm trying to figure out how best to trigger my video modal from a link in a dynamically generated navigation. 

I have a video modal in my markup that I re-use and update the src via the data-url attribute. While this works wonderfully for assigning events to links that exists on when the DOM is ready, it doesn't (of course!) when the navigation is generated via javascript, because it never sees this dynamically generated link with the data attributes assigned.

How can I trigger the modal for links that are generated this way? Is it assigning an onClick event listener to the dynamically generated link?

Thanks for any insights!

**Comment by claudia-romano** [comment]
Hi there, you can use one of the Modal custom events. You can find more info here:
https://codyhouse.co/ds/components/info/modal-window#custom-events

Cheers!

**Comment by rjdusk** [comment]
Excellent, thank you @claudia-romano that sent me in the right direction. I just had to adjust the code slightly to work within my code base. See below for anyone who happens upon this thread:

```
const figure = this.$refs.container.querySelector('.meganav-about__figure')
const modal = document.getElementById('modal-video-iframe')

function openModal(element) {
    const event = new CustomEvent('openModal', {
        detail: figure,
    })
    element.dispatchEvent(event)
}

figure.addEventListener('click', (e) => {
    e.preventDefault()
    openModal(modal)
})
```
