### ISSUE TITLE
Modal window trigger not getting focus after modal close when trigger includes elements inside

### ISSUE THREAD

**Issue by danis039** [CodyHouse/cd-modal-window-changelog#6]
Hi guys,

To replicate this issue, please browse to the modal window demo page - https://codyhouse.co/ds/components/app/modal-window - and edit in DevTools the trigger button to include, for example, a `span` element inside:

```
<button class="btn btn--primary" aria-controls="modal-name-1"><span>Show modal window</span></button>
```

When using the escape key to close the modal, the trigger should get focus, but it doesn't. This is a common scenario when using icons inside buttons, etc.

A possible solution would be to change line 35 to:
```
this.selectedTrigger = event.target.closest(focusableElString);
```

Let me know what you think.

Cheers!

**Comment by claudia-romano** [comment]
Hi Daniel, thanks for the heads-up! Yes, your solution works great. Alternatively, you can use the currentTarget (rather than the target):
```
self.selectedTrigger = event.currentTarget;
```
We'll push a fix asap. Cheers!

**Comment by danis039** [comment]
Thanks, @claudia-romano! That's a much better solution! 🥳

**Comment by claudia-romano** [comment]
The component has been updated as well. Cheers!
